# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-01 21:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='chats',
        ),
        migrations.AddField(
            model_name='chat',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='activation_code',
            field=models.CharField(default='MkTXFpPvExeYFZdesQer', max_length=20),
        ),
    ]
