# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-09 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180102_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='main/static/img/profile_photo/default.png', upload_to='main/static/img/profile_photo/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='activation_code',
            field=models.CharField(default='DLSSeG79DQqEWn3J7dB6', max_length=20),
        ),
    ]
