# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-25 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20171223_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_recovery_code',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='activation_code',
            field=models.CharField(default='YQgd37YhBNJQhWyKfzBV', max_length=20),
        ),
    ]
