# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-09 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180109_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_code',
            field=models.CharField(default='f4AFHYgpUMjWGFWYSBks', max_length=20),
        ),
    ]
