# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-09 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180109_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_code',
            field=models.CharField(default='t8F49htsUALPwuBzxcjH', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='static/img/profile_photo/default.png', upload_to='static/simg/profile_photo/'),
        ),
    ]
