# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-09 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180109_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_code',
            field=models.CharField(default='h38V8JT6Knw5TrdCythv', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='profile_photo/default.png', upload_to='profile_photo'),
        ),
    ]
