# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-09 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180109_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_code',
            field=models.CharField(default='K4QUhBFW9c28W5ZTcwLu', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='/profile_photo/default.png', upload_to='main/static/profile_photo/<django.db.models.fields.EmailField>'),
        ),
    ]
